-- macOS 发现页联调样本：上海附近、带预期成果，供 19900001234 浏览/申请
-- 发布者：13884283997 (29844721-...)

DO $$
DECLARE
  publisher TEXT := '29844721-ff7f-4340-b60d-d68a73c5d6c7';
BEGIN
  INSERT INTO "Demand" (
    id, "userId", title, description, "minPrice", category, "serviceType",
    "cityCode", "regionId", "isCertifiedOnly", stage, "coverImage", "amountEstimate",
    "expireAt", status, "mediaUrls", "applicantCount", "isExample", "isPublic",
    "visibilityWindow", "visibleUntil", "expectedOutcome", deposit, "maxApplicants",
    tags, "tagsConfirmed", "fuzzyLat", "fuzzyLng", "lifecycleStage", paths
  ) VALUES
  (
    'macos-discover-demo-001',
    publisher,
    '品牌视觉升级 · Logo 与产品图标',
    '希望在一周内完成品牌 Logo 微调与 macOS / iOS 双端图标导出，含源文件与规范说明。',
    800,
    '视觉设计',
    'ONLINE',
    '310000',
    310000,
    false,
    'active',
    '/uploads/card-covers/10012.jpg',
    1200,
    NOW() + INTERVAL '14 days',
    'ACTIVE',
    '[]'::jsonb,
    2,
    false,
    true,
    15,
    NOW() + INTERVAL '15 minutes',
    '交付可上线的品牌图标包（SVG/PNG）与一页使用规范',
    0,
    10,
    ARRAY['品牌设计', '图标', 'macOS'],
    true,
    31.2304,
    121.4737,
    'ACTIVE',
    ARRAY['cat:视觉设计', 'attr:servicetype=online']
  ),
  (
    'macos-discover-demo-002',
    publisher,
    '用户访谈 · 早期产品验证',
    '需要 8-12 名目标用户深度访谈，整理洞察报告与机会点清单，支持远程或上海线下。',
    500,
    '用户研究',
    'OFFLINE',
    '310000',
    310000,
    false,
    'active',
    '/uploads/card-covers/10008.jpg',
    900,
    NOW() + INTERVAL '10 days',
    'ACTIVE',
    '[]'::jsonb,
    1,
    false,
    true,
    15,
    NOW() + INTERVAL '15 minutes',
    '结构化访谈纪要 + 3 条可执行产品建议',
    0,
    8,
    ARRAY['用户访谈', '洞察报告', '上海'],
    true,
    31.2244,
    121.4692,
    'ACTIVE',
    ARRAY['cat:用户研究', 'attr:servicetype=offline', 'rgn:310000']
  ),
  (
    'macos-discover-demo-003',
    publisher,
    '竞品对比分析 · 服务卡整理',
    '整理 5 款同类产品的功能与定价对比，输出 Excel 与服务卡摘要，供内部评审使用。',
    350,
    '产品研究',
    'ONLINE',
    '310000',
    310000,
    false,
    'active',
    '/uploads/card-covers/10015.jpg',
    450,
    NOW() + INTERVAL '7 days',
    'ACTIVE',
    '[]'::jsonb,
    0,
    false,
    true,
    15,
    NOW() + INTERVAL '15 minutes',
    '竞品对比表 + 一页 executive summary',
    0,
    10,
    ARRAY['竞品分析', '产品研究'],
    true,
    31.2368,
    121.4801,
    'ACTIVE',
    ARRAY['cat:产品研究', 'attr:servicetype=online']
  )
  ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    "expectedOutcome" = EXCLUDED."expectedOutcome",
    "expireAt" = EXCLUDED."expireAt",
    "visibleUntil" = EXCLUDED."visibleUntil",
    status = EXCLUDED.status,
    stage = EXCLUDED.stage,
    "isPublic" = true,
    "fuzzyLat" = EXCLUDED."fuzzyLat",
    "fuzzyLng" = EXCLUDED."fuzzyLng";
END $$;
